### find all patients
GET http://localhost:3003/api/patients

### create a new patient
POST http://localhost:3003/api/patients
Content-Type: application/json

{
  "name": "Francisco Figueroa Casas",
  "dateOfBirth": "2002-07-19",
  "gender": "male",
  "occupation": "Student",
  "ssn": "44306801"
}

### find a specific patient
GET http://localhost:3003/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667